[default]
projectname = BDA-Output-Test
projectdescription = Testing the BDA Output and function
ProjectStage=DEVELOPMENT
aws_region = us-east-1
; vector-db-admin-secret = 
; aws_client_secretsmanager=secretsmanager

input_bucket_name = cmcs-contract-rag

input_prefix =

output_bucket = cmcs-contract-rag-post-processing
output_prefix = bdaoutput/
full_refresh = True

code_bucket_name =  cmcs-contract-llm-pipeline-code

temp_bucket_name=  cmcs-contract-llm-pipeline-temp
DataAutomationV=us.data-automation-v1


foundation_llm_model_id = us.amazon.nova-pro-v1:0
model_id_bedrock_embeddings=amazon.titan-embed-text-v2:0
PGVector = PGVECTOR


BDATextOutputFolder = BDATextOutput/
BDATableOutputFolder = BDATableOutput/
BDAImageOutputFolder = BDAImageOutput/

BDATextOutputFilename   = Output-BDA-texts.json
BDATableOutputFilename = Output-BDA-tables.json
BDAImageOutputFilename = Output-BDA-images.json

TempFolder=processtempfiles/
SummaryLogFolder=summarylog/
APP_LOG_LEVEL = DEBUG

OutPutExcelJsonFolderPreProcess=output_excel_json/


RagSplitOutPutBucket = cmcs-contract-rag-post-processing
RagSplitOutPutFolder = rag_output/
RagSplitOutPutFile = split_final_document_data.json


embedding_dimension=1536
embedding_batch_size=20
db_pool_min=2
db_pool_max=5

model_id_bedrock_profile_embed = us.cohere.embed-v4:0
model_id_cohere_reranker=cohere.rerank-v3-5:0


